name: ssh
on: 
 workflow_dispatch

jobs:
    job1:
        strategy:
         matrix:
          target_arch: [x86_64]
        runs-on: ubuntu-latest
        steps:
        - name: Starting Tmate
          run: |
                sudo apt update 
                sudo apt install neofetch 
                wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz &> /dev/null
                tar -xf tmate-2.4.0-static-linux-amd64.tar.xz
                echo -e "\nexport PS1='\u@\h:\w\$ '" | sudo tee -a /etc/bash.bashrc
                echo -e "\nneofetch" | sudo tee -a /etc/bash.bashrc
                sudo /usr/sbin/sshd
                $PWD/tmate-2.4.0-static-linux-amd64/tmate -F -k ${{ secrets.TMATE_API }} -n git
      
